### ISSUE TITLE
How do you use this extension?

### ISSUE THREAD

**Issue by cesar-moya** [ciiqr/vscode-extensions#1]
What is the file extension that is supported?

**Comment by ciiqr** [comment]
I'm guessing you're asking about the note extension? (there's a few extensions in this repo).
It's configured for `.txt` and `.todo` files by default (though other extensions could potentially override this default).

For other files, you can change the language mode:
<img width="168" alt="image" src="https://github.com/ciiqr/vscode-extensions/assets/2072378/60498561-bb57-47f2-b1e0-e86b7c181ca6">
to:
<img width="115" alt="image" src="https://github.com/ciiqr/vscode-extensions/assets/2072378/0e039342-5058-4532-b41d-0d54c1826269">

Or even change the default (also under the `Change Language Mode` command):
<img width="218" alt="image" src="https://github.com/ciiqr/vscode-extensions/assets/2072378/7539acae-f1e2-4036-a431-67f6c43e2b46">
