### ISSUE TITLE
This is not working as expected

### ISSUE THREAD

**Issue by merbin2012** [ciiqr/vscode-extensions#2]
The app icon only changed, the content color is not changed. Do I need to do any changes in settings?
Please check the below image

![screenshot-nimbusweb me-2024 05 30-11_16_59](https://github.com/ciiqr/vscode-extensions/assets/3687184/bfe52f59-da15-4506-9c64-7f275513a9da)

**Comment by ciiqr** [comment]
1. so the colours that are used by default are based on the theme your using, I've chosed defaults that work with my preferred theme, but it's impossible to account for every theme, and in your case it looks like your theme doesn't necessarily have different colours for all the different identifiers. You could try overriding the colours used (check out the **Customize** section of the extension readme: https://marketplace.visualstudio.com/items?itemName=ciiqr.note-syntax#customize)
2. the various prefixes require a space before any other words (with the exception of the comment `#` prefix), so lines 6 & 7 in your screenshot aren't considered valid


If you want a reference point for the prefixes supported, and maybe just a file for testing your theme overrides try downloading the sample file from the repo here: https://github.com/ciiqr/vscode-extensions/blob/main/packages/note-syntax/sample.txt

Let me know if I can help with anything else :)

**Comment by merbin2012** [comment]
I have used the sample text also, but it shows the same output. I will check with the customize option and let you know the result.

Thanks

**Comment by merbin2012** [comment]
Thank you, it is working now
